
== REGOLE AGGIUNTIVE

Quelle che seguono fanno parte del gioco a tutti gli effetti, ma si consiglia di fare pratica con un paio di partite prima iniziare a usarle.

Segnalino “Deus Ex-Machina”::
Il giocatore che lo possiede può usare questo Segnalino dopo un lancio di dadi (siano essi 3 oppure 5) per ripetere un lancio dello stesso numero di dadi. Questo Segnalino viene assegnato all’ultimo giocatore che inizia.
Dopo che è stato usato passa al giocatore alla propria destra a meno che non sia stato usato per ripetere il tiro di un giocatore avversario, allorché il Segnalino andrà a lui.

7 vizi capitali - Il troppo stroppia!:: Non si possono avere più di 7 Segnalini per simbolo. Se un giocatore arriva a 8 Segnalini anche solo con un simbolo, perde la partita e esce dal gioco. Anche in questo caso non può mostrare che ruolo ricopriva.

Festa della Porchetta - Si mangia!:: Se con il tiro dei dadi escono 5 simboli uguali di Popolo, Torre, Libro o Mortadella, tutti i giocatori acquisiscono immediatamente 1 Segnalino corrispondente al simbolo del dado. Nel caso si verificassero le condizioni di vittoria per un giocatore, vince la partita anche se non è il suo turno. Se sono più di uno i giocatori che potrebbero vincere, vince quello che avrebbe dovuto giocare prima, seguendo l’ordine orario dei turni.

Terremoto - Rrrrrumble! :: Se con il tiro dei dadi escono 5 simboli tra Ratto e Vino (ad es. 3 Ratti e 2 Vini) tutti i giocatori scartano tutti i Segnalini Torre e tutti i Segnalini Libro in gioco. Nel caso si verificassero le condizioni di vittoria per un giocatore, vince la partita anche se non è il suo turno. Se sono più di uno i giocatori che potrebbero vincere, vince quello che avrebbe dovuto giocare prima, seguendo l’ordine orario dei turni.

Carnevale - Ogni scherzo vale! :: Se con il tiro dei dadi escono 5 simboli diversi il giocatore sceglie 3 dei simboli e, invece che acquisirli dalla riserva comune, li ruba da uno o più giocatori avversari.
 
