
== ADDITIONAL RULES
The following rules are actual parts of the game, but we recommend you play the game once or twice before including them in your games.

=== Lombard Company Token
When you have this Token, you can use it after rolling the dice (either 3 or 5 dice) to reroll that same number of dice. This Token is given to the last player in the first round of the game.
After you use it, you will pass the Token to the player at your right, unless you have used it to force an opponent to reroll his own dice; in that case, he gets the Token.

=== 7 Deadly Sins - Enough is enough!
No player can have more than 7 Tokens per symbol. If a player collects 8 Tokens of any one symbol, he has lost and he must quit the game.  He cannot show the role he had until the game is over for all the players.

=== Salted Pork Feast - Let’s eat! 
If you get 5 symbols of the same type (People, Tower, Book or Bologna) when you roll the dice, each player immediately gains 1 Token with that symbol. If in doing so, a player fulfills his victory conditions, he wins the game even if this is not his turn. If more than one player would fulfill his victory conditions, the winner is the one whose turn would come first proceeding clockwise.

=== Earthquake - Rrrrrumble! 
If you get any combination of only Rat and Wine symbols (e.g. 3 Rats and 2 Wine), all players must discard their Tower and Book Tokens. If in doing so, a player fulfills his victory conditions, he wins the game even if this is not his turn. If more than one player would fulfill his victory conditions, the winner is the one whose turn would come first proceeding clockwise.

=== Feast of Fools - The Joke’s on You! 
If you get 5 different symbols when you roll the dice, you can choose 3 symbols: Instead of taking them from the common pool, you steal them from one or more opponents.

