== VARIANTI AL GIOCO BASE

Variante per 6 giocatori::
In una partita a 6 tutti i giocatori partono con 1 Segnalino Popolo e 1 Segnalino Mortadella.

Variante per 7 giocatori::
In una partita a 7 tutti i giocatori partono con 2 Segnalini Popolo e 1 Segnalino a loro scelta. Entra inoltre il ruolo speciale del Brigante, che gioca con la carta ruolo scoperta.

Brigante::
Il Brigante tira i dadi normalmente ma i simboli di Popolo, Torre, Libro e Mortadella anziché acquisirli dalla riserva al centro del tavolo li ruba agli altri giocatori. +
Inoltre il Brigante non è soggetto alla limitazione dei 7 vizi capitali e non può essere il bersaglio del Maestro dei Locandieri. + 
*Condizioni di vittoria*: Il Brigante vince acquisendo almeno 8 Segnalini uguali a scelta tra Popolo, Libro e Mortadella, e tenendo a 0 i gli altri due simboli.

Variante per 2 giocatori:: Togliere dalle carte Ruolo il Maestro dei Locandieri e il Brigante.
Alle condizioni di vittoria di ciascun giocatore ne va aggiunta una: il giocatore vince se indovina il ruolo di un altro giocatore. Se non lo indovina scarta tutti i Segnalini, la carta Ruolo viene eliminata dalla partita e il giocatore pesca una nuova carta Ruolo e ricomincia la partita passando il turno.

