
== GAME VARIANTS

6 Player Variant::
In a 6 player game, all players start with 1 People Token and 1 Bologna Token.

7 Player Variant::
In a 7-player game, all players start with 2 People Tokens and 1 Token of their choice. The Brigand special role is also added. The Brigand player will keep his role card face-up.

Brigand::
The Brigand rolls his dice as usual, but rather than acquiring his People, Tower, Book and Bologna Tokens from the central pool, he will steal them from the other players.
In addition, the Brigand is unaffected by the 7 deadly sins limitation, and he cannot be targeted by the Master Innkeeper.

Victory Conditions::
The Brigand wins as soon as he acquires 8 Tokens of the same type, choosing among People, Book and Bologna; however, he must have 0 Tokens of the remaining Token types.

2 Player Variant::
Remove the Master Innkeeper and the Brigand from the Role deck.
The following condition must be added to the victory conditions of each player: A player wins if he correctly guesses the role of another player. If his guess is wrong, though, he must discard all his Tokens, and his Role card is removed from the game. Then the player draws a new Role card, his turn ends and the game continues.

